#include <QApplication>
#include <MainWindow.h>
#include <EncryptWindow.h>
#include <DecryptWindow.h>
#include <ResultWindow.h>
#include <test.h>

#include <deroulementcryptanalysesubstitution.h>

int main(int argc, char* argv[])

{

    QApplication app(argc,argv);
    //test* window= new test();
   // encryptwindow* window= new encryptwindow();
   mainwindow* window = new mainwindow();
    //decryptwindow* window = new decryptwindow();
   //QString txt = "PARISESTLAPLUSGRANDEVILLEDEFRANCECESTAUSSILACAPITALEDUPAYSLESFRANCAISAPPELLENTPARISLAVILLELUMIEREENFRANCEILYAPARISETLAPROVINCEATTENTIONNECONFONDEZPASLAPROVINCEETLAPROVENCELAPROVENCEESTLENOMDUNEREGIONDUSUDDELAFRANCELAPROVINCECESTLAFRANCEENTIERESANSPARISDANSLENORDDELAFRANCEILYAUNEVILLEQUISAPPELLELILLECESTUNEVILLEPROCHEDELABELGIQUEDANSLOUESTDELAFRANCEPRESDELOCEANATLANTIQUEILYANANTESETDANSLESUDOUESTILYABORDEAUXLAREGIONDEBORDEAUXESTTRESCELEBREPOURSESVINSTOUJOURSDANSLESUDOUESTILYATOULOUSEONAPPELLETOULOUSELAVILLEROSEPARCEQUELESMURSDESMAISONSSONTENBRIQUESDANSLESUDESTLESGRANDESVILLESSONTMARSEILLENICEETTOULONMARSEILLEESTTRESCONNUEPOURSABOUILLABAISSEMAISAUSSIPOURSONEQUIPEDEFOOTBALLLOMCESTAUSSILUNDESPLUSGRANDSPORTSDELAMERMEDITERRANEEDANSLESTDELAFRANCEILYALAVILLEDELYONQUIESTSITUEEDANSLEDEPARTEMENTDURHONECESTUNEVILLETRESDYNAMIQUESURLEPLANECONOMIQUECULTURELETSPORTIFPUISQUONYJOUETRESBIENAUFOOTBALLDANSCETEXTEVOUSAVEZENTENDULAPHRASESUIVANTECESTAUSSILUNDESPLUSGRANDSPORTSDELAMERMEDITERRANEE";
   //resultwindow* window = new resultwindow(txt);
   // deroulementcryptanalysesub* window = new deroulementcryptanalysesub();
    //cout << "la clé : " << window->generate_m_key() << endl;

    //DeroulementCryptanalyseSubstitution* window = new DeroulementCryptanalyseSubstitution("LOCOFNSDOLBNSFNLORSBZBCOMJKYBKVKNBRSBSYCONTFBNNBIKFOXYFCKNBFMXJYSONTBXOYSFTKLFYBTBCZBYNFYBCONNBCLBCRYONOFCJRRYBNSKNXBSFSTOZBOKLBKYOMJKYBKVTBXBSFSTOZBOKXBKSSYBKNHJKIKBSZBRLBKYCKNHFGJKJKKNBCJYSFBJKHFBNLBCSYJFCLORJFCOZXBNZDYOFMBNSZBCUBNCZBCUJSCZBLFMOUFNOSFJNBSZBCMJPBNCZBTWOTKNTBLOXBKSSYBKNBCJFYBYJMONSFIKBZONCKNYBCSOKYONSODBTDKBCKYLOCBFNBXJKYLBCKNCKNCFMXLBHOFCBYTWONUCJKCKNXJYTWBXJKYLBCOKSYBCTBCSTBIKFROFSXBKSSYBLBCKTTCZBTBSSBRSBYFBNNBCSZTFZTWOTKNROFSTJMMBFLDBKSBSTJNSYOFYBMBNSLOXLKXOYSZBCRSBCTJMMBXIKBCNJLJKLBNJKDBLONTBCSKNBRSBIKFNBCBRSBXOCBNROMFLLBXOCIKBCSFJNZBMMBNBYLBCBNRONSCTBGJKYLTBCSLONJKNJKIKFCBNJTTKXBBSTBKVIKFNJNSXOCZBXBSFSOMFBSHFBNFLCJNSLBTWJFVBNSYBCJYSFYBNSYBTLFHOSOFYBCJKSBNFYLOTWONZBLLBBSTWBEDJKCTBCSTJMMBNSTJMMBNSRSBSJNLOCOFNSDOLBNSFNJRRYBEDJKCZBCRLBKYCJKOKSYBTWJCBTBSSBRSBBVFCSBSBLLBOKCCFZONCDJSYBXOPC");
    //window->new_text();

    window->show();
   /* string S = "SAEFIoiijIOIEGA";
    for(int i = 0 ; i < S.length() ; i++)
    {
        S[i] = std::toupper(S[i],std::locale());
    }
    std::cout << S << endl;*/

    return app.exec();
}
